name: anmolsethi
description: My Package.
version: 0.0.1
author: Anmol Sethi
homepage: https://github.com/AnmolSethi/AnmolSethiPackage

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  flutter_statusbarcolor_ns: ^0.3.0-nullsafety
  fluttertoast: ^8.0.1-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
